targets:
  $default:
    builders:
      mockito|mockBuilder:
        enabled: true
        generate_for:
          include:
            - test/**_test.dart
            - test/test_helper.dart
          exclude:
            - test/**/*.mocks.dart
        options:
          # Mockito builder opcije
          build_extensions:
            '^test/{{}}.dart': 'test/{{}}.mocks.dart'
          source_gen:
            options:
              any_map: true
              checked: true
              field_rename: snake
              generic_argument_factories: true 
          generate_for:
            include:
              - test/**_test.dart
              - test/test_helper.dart
          build_extensions:
            '^test/{{}}.dart': 'test/{{}}.mocks.dart' 