name: secure_event_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  injectable: ^2.3.0
  get_it: ^7.6.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  mockito: ^5.4.2
  meta: ^1.9.1
  equatable: ^2.0.5
  async: ^2.11.0
  collection: ^1.17.1
  rxdart: ^0.27.7
  uuid: ^3.0.7
  path_provider: ^2.1.1
  battery_plus: ^4.0.2
  auto_route: ^7.8.0
  shared_preferences: ^2.2.0
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  synchronized: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.3.0
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  mockito: ^5.4.2
  riverpod_generator: ^2.3.9
  test: ^1.24.9
