name: secure_event_app
description: A secure event communication app.

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  test: ^1.24.0
  encrypt: ^5.0.3
  path_provider: ^2.1.1
  pdf: ^3.10.7
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
